### ISSUE TITLE
Bug in node-apk-parser module (Index out of range) (Android Studio 3.0 - Latest Gradle)

### ISSUE THREAD

**Issue by snap608** [Microsoft/google-play-vsts-extension#81]
I have a ZipAligned and signed APK. When I execute the task `Google Play - Release` I get the following error:

```
...
Task         : Google Play - Release
Version      : 1.119.0
...
apkFile=S:\Agent\_work\10\s\output\release-signed\*.apk
Main APK pattern: S:\Agent\_work\10\s\output\release-signed\*.apk
check path : S:/Agent/_work/10/s/output/release-signed/app-release-signed-zipaligned.apk
task result: Failed
RangeError: Index out of range
````

The error occures at line 45 in `GooglePlay.js`:
```
let mainVersionCode = apkParser.readFile(apkFile).readManifestSync().versionCode;
```
So it seems like it orginate from the `node-apk-parser` module.

I have also verified the `AndroidManifest.xml`-file to be correct and contain all information needed (manual upload to Google Play of the same APK works).

The build agent runs Windows.

Any tip to solve this?

**Comment by lkillgore** [comment]
Hi @snap608, I *may* have seen a similar error before (not in this task) that was fixed by updating the version of NPM and Node.  It seems like you have you are hosting your own build agent.  Which version of the build agent are you running?

Also, is there any way for you to find out if this is project or file specific?  Or, is this error happening on any APK on your build agent?

**Comment by snap608** [comment]
Hi @lkillgore. I have updated node to `6.11.4` and npm to `5.5.1` now and restarted the agent but the same issue is present.

You are right that we're running our own build agent (Windows). It's version is `2.123.0`.

I have also tried to run this on a different build agent (Mac) with the same result.

I have created a build script from scratch for this for testing including one super-simple app (APK) that I know should work. But the same happens.

Also double checked Endpoints the task is communicating with (Google).

Almost at the stage of debuging the GooglePlayRelease task. Hehe. :)

**Comment by lkillgore** [comment]
Hi @snap608, I spent a while today trying to figure out how we can get on the same page.  I tried putting together a simple project we could both try to release, but I don't think that strategy will work after all.

One thing that would be helpful is if you could run your build on the VS2017 Hosted pool.  That would rule out (or limit to) 'my machine' / 'your machine' issues.

Do you have any ideas?

**Comment by snap608** [comment]
Hi @lkillgore. :)

I'm putting together a tiny node project first to run the `node-apk-parser` alone to check if it has a bug when parsing the APK. It looks like the `node-apk-parser` used is from Dec 2016. At least to rule that out.

I have tested running the whole build script on a hosted agent but the project need gradle 4.1. Another blocker there... hehe. I'll try to make a shorter build script that just pull the APK artifacts from our repo . and run GooglePlayRelease task.

Be right back. :)

**Comment by lkillgore** [comment]
Hi @snap608, FWIW, that bug should be fixed in the agent this week.  (In case you decide to try it out on the hosted machine again and it magically gets by that issue.)

**Comment by Banders2** [comment]
Hi @snap608 I'm now facing the exact same problem did you manage to find a solution?

@lkillgore I just tried building with the Hosted 2017, but it seems like they have still not been updated to the versions:  [Android SDK Platform 26, Android SDK Build-Tools 26.0.2].

**Comment by snap608** [comment]
Hi. Sorry for the minor radio silence. :)

I have tried to debug the `node-apk-parser` with no success yet (had just an hour to spare to look into it).

@Banders2 I tested a older version of the app/APK (pre Android studio 3.0) and it worked. So there is something that have changed. I'm also able to upload a APK manually to Google Play that is compiled using Android studio 3.0.

@lkillgore Tested the Hosted 2017 agents once every day with same license error. It will probably work soon. Hehe.

**Comment by snap608** [comment]
Android Studio 3.0 (build 171.4408382) is now released (stable channel). Going to do a test by updating one of our build agents and see if it resolve anything. BRB.

**Comment by lkillgore** [comment]
@snap608, I have it on good authority that the fix for the Hosted image should finish rolling out today.  Sorry it's taken so long!

**Comment by snap608** [comment]
@lkillgore Update on the Hosted 2017 agent. The `License` blocker is gone. `Android SDK Platform 26, Android SDK Build-Tools 26.0.2` and `Gradle 4.1` install is successful. :)

But I do get the same `Index out of range´ error using the Hosted VS 2017 agent.

**Comment by snap608** [comment]
The bug is indentified by multiple users in `node-apk-parser`.

Source: https://github.com/arthur-zhang/node-apk-parser/issues/4

**Comment by snap608** [comment]
@lkillgore Not sure how to proceed with resolving this bug. Any ideas? :)

**Comment by lkillgore** [comment]
Hi @snap608, I didn't mean to go dark on you for the last couple of weeks. :)

Currently, we're deciding on our path forward.  Likely our solution will be one of the last two options you suggested.  Or, possibly we'll write our own.  Unfortunately, none of these are quick solutions. :(

I'm not sure the best idea to get you unblocked in the meantime.  One option: you could try to clone this repo yourself and remove the reference to readManifestSync().  It's only used for getting the package name and version, and if your project is simple this could work for you.

I'll post back when I have updates.

**Comment by snap608** [comment]
@lkillgore Thanks for the response. I'll probably do a fork myself of the `node-apk-parser` repo and try to fix the issue. I'll update you if I'm successful. :)

**Comment by samuelgodbout** [comment]
Hi @snap608 ,
Have you been able to fix the issue? I'm facing the same problem. :(

**Comment by bingzer** [comment]
Same problem here - any workaround?

**Comment by MateusLB** [comment]
Same problem here =(

**Comment by snap608** [comment]
I have tried to look into the `node-apk-parser` used to try to debug the issue with no success so far. :/

**Comment by madhurig** [comment]
We have this item on our backlog and hope to fix it in the next release (probably early January). Sorry for the inconvenience. 

Thanks,
Madhuri

**Comment by AntSwift** [comment]
Hi @madhurig, is there a more specific release date available? I can manually release for the time being but this isn't a good long term solution.

Thanks,
Ant

**Comment by madhurig** [comment]
@AntSwift: We have the work scheduled, will update you once we have more details on the timeline. Sorry for the inconvenience.

Thanks,
Madhuri

**Comment by danports** [comment]
I'm running into the same problem - would love to be able to use this extension, since it looks great otherwise. 😁

**Comment by lkillgore** [comment]
Hi all (specifically @AntSwift because you asked for a more specific release date)! I have a PR out for this: https://github.com/Microsoft/google-play-vsts-extension/pull/87.  I'm going through some QA on it now.  It should be released in the next day or two.

**Comment by lkillgore** [comment]
Hi all!  The fixes to the google play extension are being published right now (version 1.129.0).  Apologies for the delay in getting this fix out.  Please let us know if you run into any issues using it!

**Comment by snap608** [comment]
Hi!

Verified working for us. No changes needed to our build scripts pre. Android Studio v3.0 update.

Thanks! :)

**Comment by AntSwift** [comment]
@lkillgore Thanks for the responses and updates. Worked perfectly without any changes.
